# Verifying yaml files: http://www.yamllint.com/ or https://github.com/adrienverge/yamllint

language: csharp
solution: ExifLibrary.sln

branches:
  only:
  - master

matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      env: CONFIGURATION=Release TARGET=netstandard1.3
    - dotnet: 2.0.0
      mono: none
      os: osx
      osx_image: xcode8.3
      env: CONFIGURATION=Release TARGET=netstandard1.3

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "current ulimit is `ulimit -n`...";
      ulimit -n 1024;
      echo "new limit `ulimit -n`";
    fi
  - dotnet restore

script:
  - dotnet build -f $TARGET -c $CONFIGURATION ExifLibrary/ExifLibrary.csproj

notifications:
  email: false